Changes for Junebug
praekeltfoundation/oneplus pull request #536
Opened 2018-10-04 13:57 UTC by FredJEhlers

2018-10-04 20:27 UTC, miltontony requested changes
Similar review to MobileU. Please remove the hardcoded values

2018-10-04 20:27 UTC, miltontony commented on oneplusmvp/settings.py
> +JUNEBUG_PASSWORD = "DbAOTBsm4zXbU10x"
Please leave all these fields blank. Secondly, they should be read from ENV

2018-10-04 20:27 UTC, miltontony commented on oneplusmvp/settings.py
> +JUNEBUG_CHANNEL_ID = os.environ.get("JUNEBUG_CHANNEL_ID", "ab79e9c5-7d15-440f-8bd0-6a0e2d2445b1/")
These should preferably be blank or dummy data

2018-10-04 20:27 UTC, miltontony commented on oneplusmvp/settings.py
> +# VUMI_GO_ACCOUNT_TOKEN = "vaiToa6c"
I don't know why these details were ever committed into a public repo. Instead of commenting out, please delete

2018-10-10 05:28 UTC, miltontony approved these changes
I think my comments have been resolved. @rudigiesler happy for you to give this a once over.
Travis is still failing though.

2018-10-10 08:07 UTC, rudigiesler reviewed
A few comments, I think the big one is around metrics. I think the fact that the metric calls are being mocked means that the tests are passing, but when we actually try to run this, it will fail.

2018-10-10 08:07 UTC, rudigiesler commented on oneplus/tests/test_general_tests.py
> +    def assert_in_metric_logs(self, metric, aggr, value, temp_handler):
I seems like we've removed all calls to this function, so we can probably also just remove this function.

2018-10-10 08:07 UTC, rudigiesler commented on oneplus/utils.py
> +            api_url=settings.JUNEBUG_BASE_URL+settings.JUNEBUG_CHANNEL_ID+settings.JUNEBUG_ACCOUNT_NUMBER
The `HttpApiSender` doesn't take in the parameters `username`, `password`, and `api_url`: https://go-http-api.readthedocs.io/en/latest/messaging-api.html#go_http.send.HttpApiSender .

Also, Junebug has a different API to Vumi Go, so it won't understand requests from the Vumi Go client. It also doesn't have a metric store, nor does it have a way to receive metrics, so we shouldn't be sending any metrics to it.

2018-10-10 08:07 UTC, rudigiesler commented on ve26/djcelery/static/djcelery/style.css
> +}
These seem to be files included from a virtual environment. We probably don't want to commit any files from the virtual environment into the repository

2018-10-12 17:19 UTC, rudigiesler approved these changes

2018-10-12 17:20 UTC, merged